name: p2v
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - cmake>=3.26
  - git
  - cuda-toolkit=12.8.*
  - viser
  - imageio
  - pip:
      # Make PyTorch wheels available
      - --extra-index-url https://download.pytorch.org/whl/cu128

      # Exact PyTorch stack (CUDA 12.8 wheels)
      - torch==2.9.0
      - torchvision==0.24.0

      - tqdm
      - opencv-python
      - pybind11
      