name: aeroSplat
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - cmake>=3.26
  - git
  - cuda-toolkit=12.8.*
  # GStreamer RTSP dependencies
  - gstreamer
  - gst-plugins-base
  - gst-plugins-good
  - gst-plugins-bad
  - gst-plugins-ugly
  - gst-libav
  - gst-python
  - pygobject
  - pip:
      # Make PyTorch wheels available
      - --extra-index-url https://download.pytorch.org/whl/cu128

      # Exact PyTorch stack (CUDA 12.8 wheels)
      - torch==2.9.0
      - torchvision==0.24.0

      # objaverse render dependencies
      - requests
      - pandas
      - pyarrow
      - tqdm
      - loguru
      - fsspec>=2022.11.0
      - gputil==1.4.0
      - fire
      - setuptools
      - pillow>=11.3.0
      - matplotlib>=3.10.8
      - opencv-python>=4.12.0.88
      - ipykernel
      - prometheus-client
      - hydra-core
      # inference dependencies
      - pytorch-lightning
      - jaxtyping
      - dacite
      - scikit-image
      - scipy==1.16.3
      - sk-video
      - e3nn
      - lpips
      - wandb
      - colorspacious
      - moviepy==1.0.3
      - plyfile
      - ./stage-2_3DGS/depthsplat/diff-gaussian-rasterization-modified
      # depthsplat misc
      - beartype
      - colorama
      - einops
      - tabulate
      - xformers