name: aeroSplat
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy<2.*
  - cmake>=3.26
  - git
  - cuda-toolkit=12.8.*
  - pip:
      # Make PyTorch wheels available
      - --extra-index-url https://download.pytorch.org/whl/cu128

      # Exact PyTorch stack (CUDA 12.8 wheels)
      - torch==2.9.0
      - torchvision==0.24.0

      # objaverse render dependencies
      - requests
      - pandas
      - pyarrow
      - tqdm
      - loguru
      - fsspec>=2022.11.0
      - gputil==1.4.0
      - fire
      - setuptools
      - pillow>=12.0.0
      - matplotlib>=3.10.8
      - opencv-python>=4.12.0.88
      - ipykernel